apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: esdata
  name: es-data
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: esdata
  template:
    metadata:
      labels:
        name: esdata
    spec:
      containers:
      - name: esdata
        image: elasticsearch:latest